FROM php:8.0-fpm

RUN apt-get update && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*

# Copier code source
COPY ./src /var/www/html

# Copier config nginx
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Donner droits
RUN chown -R www-data:www-data /var/www/html

EXPOSE 81

# Script de démarrage qui lance php-fpm + nginx
CMD php-fpm -D && nginx -g "daemon off;"